"""added link between medialink and activity

Revision ID: 075cc469dbd7
Revises: d3570fb083b5
Create Date: 2018-04-29 07:55:57.095351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '075cc469dbd7'
down_revision = 'd3570fb083b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media_link', sa.Column('event_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'media_link', 'event', ['event_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'media_link', type_='foreignkey')
    op.drop_column('media_link', 'event_id')
    # ### end Alembic commands ###
