"""Image links

Revision ID: 125486c56d64
Revises: 9dad486a0e8e
Create Date: 2022-11-30 01:30:18.161828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '125486c56d64'
down_revision = '9dad486a0e8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image_link',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(length=80), nullable=True),
    sa.Column('filename', sa.String(length=200), nullable=True),
    sa.Column('url', sa.String(length=512), nullable=True),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('is_cover', sa.Boolean(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('bio_person_id', sa.Integer(), nullable=True),
    sa.Column('bio_musical_ensemble_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bio_musical_ensemble_id'], ['bio_musical_ensemble.id'], ),
    sa.ForeignKeyConstraint(['bio_person_id'], ['bio_person.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('image_link')
    # ### end Alembic commands ###
