"""added instrument to musical piece

Revision ID: 15ade35b9406
Revises: 7dc16408a6d9
Create Date: 2018-08-10 22:40:05.911121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15ade35b9406'
down_revision = '7dc16408a6d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('musical_piece', sa.Column('instrument_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'musical_piece', 'instrument', ['instrument_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'musical_piece', type_='foreignkey')
    op.drop_column('musical_piece', 'instrument_id')
    # ### end Alembic commands ###
