"""empty message

Revision ID: 162adb16f882
Revises: 4f19165fafed
Create Date: 2018-07-29 22:27:33.110167

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '162adb16f882'
down_revision = '4f19165fafed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media_link', sa.Column('filename', sa.String(length=200), nullable=True))
    op.add_column('media_link', sa.Column('url', sa.String(length=512), nullable=True))
    op.drop_column('media_link', 'link')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media_link', sa.Column('link', mysql.VARCHAR(length=200), nullable=True))
    op.drop_column('media_link', 'url')
    op.drop_column('media_link', 'filename')
    # ### end Alembic commands ###
