"""empty message

Revision ID: 33e5a30f8cd3
Revises: b3f09cef76dc
Create Date: 2018-07-07 00:12:03.181093

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '33e5a30f8cd3'
down_revision = 'b3f09cef76dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('musical_piece', sa.Column('composer_id', sa.Integer(), nullable=True))
    op.drop_constraint('musical_piece_ibfk_1', 'musical_piece', type_='foreignkey')
    op.create_foreign_key(None, 'musical_piece', 'person', ['composer_id'], ['id'])
    op.drop_column('musical_piece', 'author_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('musical_piece', sa.Column('author_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'musical_piece', type_='foreignkey')
    op.create_foreign_key('musical_piece_ibfk_1', 'musical_piece', 'person', ['author_id'], ['id'])
    op.drop_column('musical_piece', 'composer_id')
    # ### end Alembic commands ###
