"""Added cycles

Revision ID: 3f142d733079
Revises: 15ade35b9406
Create Date: 2018-09-04 01:03:41.284742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f142d733079'
down_revision = '15ade35b9406'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cycle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('event', sa.Column('cycle_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'event', 'cycle', ['cycle_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'event', type_='foreignkey')
    op.drop_column('event', 'cycle_id')
    op.drop_table('cycle')
    # ### end Alembic commands ###
