"""nombre completo, nacimiento y muerte

Revision ID: 459520e7afdc
Revises: a0247f25e276
Create Date: 2022-09-07 17:05:25.614861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '459520e7afdc'
down_revision = 'a0247f25e276'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bio_person', sa.Column('nacimiento_y_muerte', sa.String(length=1000), nullable=True))
    op.add_column('bio_person', sa.Column('nombre_completo', sa.String(length=400), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bio_person', 'nombre_completo')
    op.drop_column('bio_person', 'nacimiento_y_muerte')
    # ### end Alembic commands ###
