"""Added gender to person. Changed birth/death dates for years

Revision ID: 48beb57944df
Revises: dacc744dc3c8
Create Date: 2018-08-10 13:42:30.942050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48beb57944df'
down_revision = 'dacc744dc3c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gender',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('person', sa.Column('birth_year', sa.Date(), nullable=True))
    op.add_column('person', sa.Column('death_year', sa.Date(), nullable=True))
    op.drop_column('person', 'birth_date')
    op.drop_column('person', 'death_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('death_date', sa.DATE(), nullable=True))
    op.add_column('person', sa.Column('birth_date', sa.DATE(), nullable=True))
    op.drop_column('person', 'death_year')
    op.drop_column('person', 'birth_year')
    op.drop_table('gender')
    # ### end Alembic commands ###
