"""empty message

Revision ID: 48e7733a4a8f
Revises: 7a062132aee9
Create Date: 2022-08-31 00:50:08.414412

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '48e7733a4a8f'
down_revision = '7a062132aee9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bio_person')
    op.drop_table('bio_musical_ensemble')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bio_musical_ensemble',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('musical_ensemble_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('investigacion_autores', mysql.VARCHAR(length=800), nullable=True),
    sa.Column('investigacion_fecha', mysql.VARCHAR(length=80), nullable=True),
    sa.Column('investigacion_notas', mysql.TEXT(), nullable=True),
    sa.Column('fundacion', mysql.VARCHAR(length=800), nullable=True),
    sa.Column('termino', mysql.VARCHAR(length=800), nullable=True),
    sa.Column('integrantes', mysql.VARCHAR(length=2000), nullable=True),
    sa.Column('repertorio', mysql.TEXT(), nullable=True),
    sa.Column('premios', mysql.TEXT(), nullable=True),
    sa.Column('publicaciones', mysql.TEXT(), nullable=True),
    sa.Column('biografia', mysql.TEXT(), nullable=True),
    sa.Column('bibliografia', mysql.TEXT(), nullable=True),
    sa.Column('archivos', mysql.TEXT(), nullable=True),
    sa.Column('discografia', mysql.TEXT(), nullable=True),
    sa.Column('links', mysql.TEXT(), nullable=True),
    sa.Column('otros', mysql.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['musical_ensemble_id'], ['musical_ensemble.id'], name='bio_musical_ensemble_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('bio_person',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('person_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('investigacion_autores', mysql.VARCHAR(length=800), nullable=True),
    sa.Column('investigacion_fecha', mysql.VARCHAR(length=80), nullable=True),
    sa.Column('investigacion_notas', mysql.TEXT(), nullable=True),
    sa.Column('familia', mysql.TEXT(), nullable=True),
    sa.Column('profesion', mysql.VARCHAR(length=400), nullable=True),
    sa.Column('instrumento', mysql.VARCHAR(length=2000), nullable=True),
    sa.Column('estudios_formales', mysql.TEXT(), nullable=True),
    sa.Column('estudios_informales', mysql.TEXT(), nullable=True),
    sa.Column('trabajo', mysql.TEXT(), nullable=True),
    sa.Column('ensambles', mysql.TEXT(), nullable=True),
    sa.Column('premios', mysql.TEXT(), nullable=True),
    sa.Column('publicaciones', mysql.TEXT(), nullable=True),
    sa.Column('biografia', mysql.TEXT(), nullable=True),
    sa.Column('bibliografia', mysql.TEXT(), nullable=True),
    sa.Column('archivos', mysql.TEXT(), nullable=True),
    sa.Column('discografia', mysql.TEXT(), nullable=True),
    sa.Column('links', mysql.TEXT(), nullable=True),
    sa.Column('otros', mysql.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], name='bio_person_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
