"""added source field to Events

Revision ID: 4a2cf65da998
Revises: 5c931a25c5c6
Create Date: 2020-05-25 00:06:04.915569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a2cf65da998'
down_revision = '5c931a25c5c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('sources', sa.String(length=2000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'sources')
    # ### end Alembic commands ###
