"""Added cycles

Revision ID: 4ef98feb0760
Revises: 15ade35b9406
Create Date: 2018-09-03 22:34:25.596719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ef98feb0760'
down_revision = '15ade35b9406'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('cycle_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'event', 'cycle', ['cycle_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'event', type_='foreignkey')
    op.drop_column('event', 'cycle_id')
    # ### end Alembic commands ###
