"""added multiple composer support and text entry

Revision ID: 5c931a25c5c6
Revises: a2207a63f2b9
Create Date: 2018-11-15 22:01:58.684871

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5c931a25c5c6'
down_revision = 'a2207a63f2b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('composer',
    sa.Column('musical_piece_id', sa.Integer(), nullable=True),
    sa.Column('person_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['musical_piece_id'], ['musical_piece.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], )
    )
    op.add_column('musical_piece', sa.Column('instrumental_lineup', sa.String(length=200), nullable=True))
    op.add_column('musical_piece', sa.Column('text', sa.String(length=200), nullable=True))
    op.drop_constraint('musical_piece_ibfk_1', 'musical_piece', type_='foreignkey')
    op.drop_column('musical_piece', 'composer_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('musical_piece', sa.Column('composer_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('musical_piece_ibfk_1', 'musical_piece', 'person', ['composer_id'], ['id'])
    op.drop_column('musical_piece', 'text')
    op.drop_column('musical_piece', 'instrumental_lineup')
    op.drop_table('composer')
    # ### end Alembic commands ###
