"""BioPerson refactored

Revision ID: 609b65aee1bb
Revises: 9092530c9048
Create Date: 2022-08-27 01:00:05.617833

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '609b65aee1bb'
down_revision = '9092530c9048'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bio_person', 'nacimiento')
    op.drop_column('bio_person', 'nombre_completo')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bio_person', sa.Column('nombre_completo', mysql.VARCHAR(length=400), nullable=True))
    op.add_column('bio_person', sa.Column('nacimiento', mysql.VARCHAR(length=800), nullable=True))
    # ### end Alembic commands ###
