"""refactors in bios

Revision ID: 7a062132aee9
Revises: 609b65aee1bb
Create Date: 2022-08-27 19:18:24.525962

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7a062132aee9'
down_revision = '609b65aee1bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bio_musical_ensemble', 'nombre_completo')
    op.drop_column('bio_musical_ensemble', 'tipo_ensamble')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bio_musical_ensemble', sa.Column('tipo_ensamble', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('bio_musical_ensemble', sa.Column('nombre_completo', mysql.VARCHAR(length=400), nullable=True))
    # ### end Alembic commands ###
