"""Increased column size of strings (more)

Revision ID: 7ec4a103f691
Revises: bb7b978c1411
Create Date: 2018-08-01 23:41:57.532039

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7ec4a103f691'
down_revision = 'bb7b978c1411'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('event', 'information',
               existing_type=mysql.VARCHAR(length=600),
               type_=sa.String(length=4000),
               existing_nullable=True)
    op.alter_column('location', 'additional_info',
               existing_type=mysql.VARCHAR(length=300),
               type_=sa.String(length=4000),
               existing_nullable=True)
    op.alter_column('location', 'address',
               existing_type=mysql.VARCHAR(length=200),
               type_=sa.String(length=300),
               existing_nullable=True)
    op.alter_column('musical_piece', 'name',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.alter_column('organization', 'additional_info',
               existing_type=mysql.VARCHAR(length=1000),
               type_=sa.String(length=4000),
               existing_nullable=True)
    op.alter_column('person', 'biography',
               existing_type=mysql.VARCHAR(length=2000),
               type_=sa.String(length=8000),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('person', 'biography',
               existing_type=sa.String(length=8000),
               type_=mysql.VARCHAR(length=2000),
               existing_nullable=True)
    op.alter_column('organization', 'additional_info',
               existing_type=sa.String(length=4000),
               type_=mysql.VARCHAR(length=1000),
               existing_nullable=True)
    op.alter_column('musical_piece', 'name',
               existing_type=sa.String(length=200),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('location', 'address',
               existing_type=sa.String(length=300),
               type_=mysql.VARCHAR(length=200),
               existing_nullable=True)
    op.alter_column('location', 'additional_info',
               existing_type=sa.String(length=4000),
               type_=mysql.VARCHAR(length=300),
               existing_nullable=True)
    op.alter_column('event', 'information',
               existing_type=sa.String(length=4000),
               type_=mysql.VARCHAR(length=600),
               existing_nullable=True)
    # ### end Alembic commands ###
