"""removed instrument_id from MusicalPiece

Revision ID: 8e0447a4542f
Revises: 4a2cf65da998
Create Date: 2020-08-29 21:12:13.644845

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8e0447a4542f'
down_revision = '4a2cf65da998'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('musical_piece_ibfk_2', 'musical_piece', type_='foreignkey')
    op.drop_column('musical_piece', 'instrument_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('musical_piece', sa.Column('instrument_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('musical_piece_ibfk_2', 'musical_piece', 'instrument', ['instrument_id'], ['id'])
    # ### end Alembic commands ###
