"""empty message

Revision ID: 8eb05838974d
Revises: ed897abe8a53
Create Date: 2022-08-24 14:20:21.535442

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8eb05838974d'
down_revision = 'ed897abe8a53'
branch_labels = None
depends_on = None


def upgrade():
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('biografia_persona')
    # op.drop_table('biografia_musical_ensemble')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('biografia_musical_ensemble',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('musicalensemble_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('investigacion_autores', mysql.VARCHAR(length=800), nullable=True),
    sa.Column('investigacion_fecha', mysql.VARCHAR(length=80), nullable=True),
    sa.Column('investigacion_notas', mysql.TEXT(), nullable=True),
    sa.Column('nombre_completo', mysql.VARCHAR(length=400), nullable=True),
    sa.Column('fundacion', mysql.VARCHAR(length=800), nullable=True),
    sa.Column('termino', mysql.VARCHAR(length=800), nullable=True),
    sa.Column('integrantes', mysql.VARCHAR(length=2000), nullable=True),
    sa.Column('tipo_ensamble', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('repertorio', mysql.TEXT(), nullable=True),
    sa.Column('premios', mysql.TEXT(), nullable=True),
    sa.Column('publicaciones', mysql.TEXT(), nullable=True),
    sa.Column('biografia', mysql.TEXT(), nullable=True),
    sa.Column('bibliografia', mysql.TEXT(), nullable=True),
    sa.Column('archivos', mysql.TEXT(), nullable=True),
    sa.Column('discografia', mysql.TEXT(), nullable=True),
    sa.Column('links', mysql.TEXT(), nullable=True),
    sa.Column('otros', mysql.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['musicalensemble_id'], ['musical_ensemble.id'], name='biografia_musical_ensemble_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('biografia_persona',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('person_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('investigacion_autores', mysql.VARCHAR(length=800), nullable=True),
    sa.Column('investigacion_fecha', mysql.VARCHAR(length=80), nullable=True),
    sa.Column('investigacion_notas', mysql.TEXT(), nullable=True),
    sa.Column('nombre_completo', mysql.VARCHAR(length=400), nullable=True),
    sa.Column('nacimiento', mysql.VARCHAR(length=800), nullable=True),
    sa.Column('fallecimiento', mysql.VARCHAR(length=800), nullable=True),
    sa.Column('familia', mysql.TEXT(), nullable=True),
    sa.Column('profesion', mysql.VARCHAR(length=400), nullable=True),
    sa.Column('instrumento', mysql.VARCHAR(length=2000), nullable=True),
    sa.Column('estudios_formales', mysql.TEXT(), nullable=True),
    sa.Column('estudios_informales', mysql.TEXT(), nullable=True),
    sa.Column('trabajo', mysql.TEXT(), nullable=True),
    sa.Column('ensambles', mysql.TEXT(), nullable=True),
    sa.Column('premios', mysql.TEXT(), nullable=True),
    sa.Column('publicaciones', mysql.TEXT(), nullable=True),
    sa.Column('biografia', mysql.TEXT(), nullable=True),
    sa.Column('bibliografia', mysql.TEXT(), nullable=True),
    sa.Column('archivos', mysql.TEXT(), nullable=True),
    sa.Column('discografia', mysql.TEXT(), nullable=True),
    sa.Column('links', mysql.TEXT(), nullable=True),
    sa.Column('otros', mysql.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], name='biografia_persona_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
