"""BioMusicalEnsemble

Revision ID: 9092530c9048
Revises: 9ac58cc15e7e
Create Date: 2022-08-25 00:38:47.099654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9092530c9048'
down_revision = '9ac58cc15e7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bio_musical_ensemble',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('musical_ensemble_id', sa.Integer(), nullable=False),
    sa.Column('investigacion_autores', sa.String(length=800), nullable=True),
    sa.Column('investigacion_fecha', sa.String(length=80), nullable=True),
    sa.Column('investigacion_notas', sa.Text(), nullable=True),
    sa.Column('nombre_completo', sa.String(length=400), nullable=True),
    sa.Column('fundacion', sa.String(length=800), nullable=True),
    sa.Column('termino', sa.String(length=800), nullable=True),
    sa.Column('integrantes', sa.String(length=2000), nullable=True),
    sa.Column('tipo_ensamble', sa.String(length=200), nullable=True),
    sa.Column('repertorio', sa.Text(), nullable=True),
    sa.Column('premios', sa.Text(), nullable=True),
    sa.Column('publicaciones', sa.Text(), nullable=True),
    sa.Column('biografia', sa.Text(), nullable=True),
    sa.Column('bibliografia', sa.Text(), nullable=True),
    sa.Column('archivos', sa.Text(), nullable=True),
    sa.Column('discografia', sa.Text(), nullable=True),
    sa.Column('links', sa.Text(), nullable=True),
    sa.Column('otros', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['musical_ensemble_id'], ['musical_ensemble.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bio_musical_ensemble')
    # ### end Alembic commands ###
