"""added gender id foreign key

Revision ID: 93583aedfb8e
Revises: 48beb57944df
Create Date: 2018-08-10 21:21:52.174545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93583aedfb8e'
down_revision = '48beb57944df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('gender_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'person', 'gender', ['gender_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'person', type_='foreignkey')
    op.drop_column('person', 'gender_id')
    # ### end Alembic commands ###
