"""Bio media links

Revision ID: 9dad486a0e8e
Revises: 459520e7afdc
Create Date: 2022-11-29 19:49:21.698486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9dad486a0e8e'
down_revision = '459520e7afdc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media_link', sa.Column('bio_musical_ensemble_id', sa.Integer(), nullable=True))
    op.add_column('media_link', sa.Column('bio_person_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'media_link', 'bio_musical_ensemble', ['bio_musical_ensemble_id'], ['id'])
    op.create_foreign_key(None, 'media_link', 'bio_person', ['bio_person_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'media_link', type_='foreignkey')
    op.drop_constraint(None, 'media_link', type_='foreignkey')
    op.drop_column('media_link', 'bio_person_id')
    op.drop_column('media_link', 'bio_musical_ensemble_id')
    # ### end Alembic commands ###
