"""empty message

Revision ID: a0247f25e276
Revises: 48e7733a4a8f
Create Date: 2022-08-31 01:00:23.770532

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a0247f25e276'
down_revision = '48e7733a4a8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bio_musical_ensemble',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('musical_ensemble_id', sa.Integer(), nullable=False),
    sa.Column('investigacion_autores', mysql.MEDIUMTEXT(charset='utf8mb4'), nullable=True),
    sa.Column('investigacion_fecha', mysql.MEDIUMTEXT(charset='utf8mb4'), nullable=True),
    sa.Column('investigacion_notas', mysql.MEDIUMTEXT(charset='utf8mb4'), nullable=True),
    sa.Column('fundacion', mysql.MEDIUMTEXT(charset='utf8mb4'), nullable=True),
    sa.Column('termino', mysql.MEDIUMTEXT(charset='utf8mb4'), nullable=True),
    sa.Column('integrantes', mysql.MEDIUMTEXT(charset='utf8mb4'), nullable=True),
    sa.Column('repertorio', mysql.MEDIUMTEXT(charset='utf8mb4'), nullable=True),
    sa.Column('premios', mysql.MEDIUMTEXT(charset='utf8mb4'), nullable=True),
    sa.Column('publicaciones', mysql.MEDIUMTEXT(charset='utf8mb4'), nullable=True),
    sa.Column('biografia', mysql.MEDIUMTEXT(charset='utf8mb4'), nullable=True),
    sa.Column('bibliografia', mysql.MEDIUMTEXT(charset='utf8mb4'), nullable=True),
    sa.Column('archivos', mysql.MEDIUMTEXT(charset='utf8mb4'), nullable=True),
    sa.Column('discografia', mysql.MEDIUMTEXT(charset='utf8mb4'), nullable=True),
    sa.Column('links', mysql.MEDIUMTEXT(charset='utf8mb4'), nullable=True),
    sa.Column('otros', mysql.MEDIUMTEXT(charset='utf8mb4'), nullable=True),
    sa.ForeignKeyConstraint(['musical_ensemble_id'], ['musical_ensemble.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bio_person',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('investigacion_autores', mysql.MEDIUMTEXT(charset='utf8mb4'), nullable=True),
    sa.Column('investigacion_fecha', mysql.MEDIUMTEXT(charset='utf8mb4'), nullable=True),
    sa.Column('investigacion_notas', mysql.MEDIUMTEXT(charset='utf8mb4'), nullable=True),
    sa.Column('familia', mysql.MEDIUMTEXT(charset='utf8mb4'), nullable=True),
    sa.Column('profesion', mysql.MEDIUMTEXT(charset='utf8mb4'), nullable=True),
    sa.Column('instrumento', mysql.MEDIUMTEXT(charset='utf8mb4'), nullable=True),
    sa.Column('estudios_formales', mysql.MEDIUMTEXT(charset='utf8mb4'), nullable=True),
    sa.Column('estudios_informales', mysql.MEDIUMTEXT(charset='utf8mb4'), nullable=True),
    sa.Column('trabajo', mysql.MEDIUMTEXT(charset='utf8mb4'), nullable=True),
    sa.Column('ensambles', mysql.MEDIUMTEXT(charset='utf8mb4'), nullable=True),
    sa.Column('premios', mysql.MEDIUMTEXT(charset='utf8mb4'), nullable=True),
    sa.Column('publicaciones', mysql.MEDIUMTEXT(charset='utf8mb4'), nullable=True),
    sa.Column('biografia', mysql.MEDIUMTEXT(charset='utf8mb4'), nullable=True),
    sa.Column('bibliografia', mysql.MEDIUMTEXT(charset='utf8mb4'), nullable=True),
    sa.Column('archivos', mysql.MEDIUMTEXT(charset='utf8mb4'), nullable=True),
    sa.Column('discografia', mysql.MEDIUMTEXT(charset='utf8mb4'), nullable=True),
    sa.Column('links', mysql.MEDIUMTEXT(charset='utf8mb4'), nullable=True),
    sa.Column('otros', mysql.MEDIUMTEXT(charset='utf8mb4'), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bio_person')
    op.drop_table('bio_musical_ensemble')
    # ### end Alembic commands ###
