"""Adding year/month/day fields for date transformation

Revision ID: a0b0573c8941
Revises: 3f142d733079
Create Date: 2018-09-20 15:10:08.996431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0b0573c8941'
down_revision = '3f142d733079'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('day', sa.Integer(), nullable=True))
    op.add_column('event', sa.Column('month', sa.Integer(), nullable=True))
    op.add_column('event', sa.Column('year', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'year')
    op.drop_column('event', 'month')
    op.drop_column('event', 'day')
    # ### end Alembic commands ###
