"""added musical ensemble support

Revision ID: a2207a63f2b9
Revises: f0de08e499f7
Create Date: 2018-11-08 00:40:47.732930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2207a63f2b9'
down_revision = 'f0de08e499f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('musical_ensemble_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('musical_ensemble',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('additional_info', sa.String(length=4000), nullable=True),
    sa.Column('musical_ensemble_type_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['musical_ensemble_type_id'], ['musical_ensemble_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('musical_ensemble_member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=True),
    sa.Column('activity_id', sa.Integer(), nullable=True),
    sa.Column('musical_ensemble_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activity.id'], ),
    sa.ForeignKeyConstraint(['musical_ensemble_id'], ['musical_ensemble.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('participant', sa.Column('musical_ensemble_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'participant', 'musical_ensemble', ['musical_ensemble_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'participant', type_='foreignkey')
    op.drop_column('participant', 'musical_ensemble_id')
    op.drop_table('musical_ensemble_member')
    op.drop_table('musical_ensemble')
    op.drop_table('musical_ensemble_type')
    # ### end Alembic commands ###
