"""Added changes for redefinition of Activities and Participants

Revision ID: b3f09cef76dc
Revises: 9e50f698b835
Create Date: 2018-07-05 23:51:30.851910

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b3f09cef76dc'
down_revision = '9e50f698b835'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('performance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('premiere_type_id', sa.Integer(), nullable=True),
    sa.Column('musical_piece_id', sa.Integer(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['musical_piece_id'], ['musical_piece.id'], ),
    sa.ForeignKeyConstraint(['premiere_type_id'], ['premiere_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('participant_performance',
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.Column('performance_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['participant_id'], ['participant.id'], ),
    sa.ForeignKeyConstraint(['performance_id'], ['performance.id'], ),
    sa.PrimaryKeyConstraint('participant_id', 'performance_id')
    )
    op.drop_table('player')
    op.drop_constraint('musical_piece_ibfk_2', 'musical_piece', type_='foreignkey')
    op.drop_column('musical_piece', 'premiere_type_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('musical_piece', sa.Column('premiere_type_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('musical_piece_ibfk_2', 'musical_piece', 'premiere_type', ['premiere_type_id'], ['id'])
    op.create_table('player',
    sa.Column('participant_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('musical_piece_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['musical_piece_id'], ['musical_piece.id'], name='player_ibfk_1'),
    sa.ForeignKeyConstraint(['participant_id'], ['participant.id'], name='player_ibfk_2'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('participant_performance')
    op.drop_table('performance')
    # ### end Alembic commands ###
