"""Increased column size of strings

Revision ID: bb7b978c1411
Revises: 162adb16f882
Create Date: 2018-08-01 23:20:02.244897

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bb7b978c1411'
down_revision = '162adb16f882'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('activity', 'name',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=40),
               existing_nullable=True)
    op.alter_column('city', 'name',
               existing_type=mysql.VARCHAR(length=25),
               type_=sa.String(length=45),
               existing_nullable=True)
    op.alter_column('country', 'name',
               existing_type=mysql.VARCHAR(length=25),
               type_=sa.String(length=45),
               existing_nullable=True)
    op.alter_column('event_type', 'name',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=40),
               existing_nullable=True)
    op.alter_column('history', 'operation',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=40),
               existing_nullable=True)
    op.alter_column('instrument', 'name',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=40),
               existing_nullable=True)
    op.alter_column('instrument_type', 'name',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=40),
               existing_nullable=True)
    op.alter_column('location', 'name',
               existing_type=mysql.VARCHAR(length=25),
               type_=sa.String(length=45),
               existing_nullable=True)
    op.alter_column('media_link', 'mime_type',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=40),
               existing_nullable=True)
    op.alter_column('premiere_type', 'name',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=40),
               existing_nullable=True)
    op.alter_column('profile', 'name',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=40),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('profile', 'name',
               existing_type=sa.String(length=40),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('premiere_type', 'name',
               existing_type=sa.String(length=40),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('media_link', 'mime_type',
               existing_type=sa.String(length=40),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('location', 'name',
               existing_type=sa.String(length=45),
               type_=mysql.VARCHAR(length=25),
               existing_nullable=True)
    op.alter_column('instrument_type', 'name',
               existing_type=sa.String(length=40),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('instrument', 'name',
               existing_type=sa.String(length=40),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('history', 'operation',
               existing_type=sa.String(length=40),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('event_type', 'name',
               existing_type=sa.String(length=40),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('country', 'name',
               existing_type=sa.String(length=45),
               type_=mysql.VARCHAR(length=25),
               existing_nullable=True)
    op.alter_column('city', 'name',
               existing_type=sa.String(length=45),
               type_=mysql.VARCHAR(length=25),
               existing_nullable=True)
    op.alter_column('activity', 'name',
               existing_type=sa.String(length=40),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=True)
    # ### end Alembic commands ###
