"""BioPerson

Revision ID: c3b8b5f3366d
Revises: 8eb05838974d
Create Date: 2022-08-24 23:45:13.849213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3b8b5f3366d'
down_revision = '8eb05838974d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bio_person',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=True),
    sa.Column('investigacion_autores', sa.String(length=800), nullable=True),
    sa.Column('investigacion_fecha', sa.String(length=80), nullable=True),
    sa.Column('investigacion_notas', sa.Text(), nullable=True),
    sa.Column('nombre_completo', sa.String(length=400), nullable=True),
    sa.Column('nacimiento', sa.String(length=800), nullable=True),
    sa.Column('familia', sa.Text(), nullable=True),
    sa.Column('profesion', sa.String(length=400), nullable=True),
    sa.Column('instrumento', sa.String(length=2000), nullable=True),
    sa.Column('estudios_formales', sa.Text(), nullable=True),
    sa.Column('estudios_informales', sa.Text(), nullable=True),
    sa.Column('trabajo', sa.Text(), nullable=True),
    sa.Column('ensambles', sa.Text(), nullable=True),
    sa.Column('premios', sa.Text(), nullable=True),
    sa.Column('publicaciones', sa.Text(), nullable=True),
    sa.Column('biografia', sa.Text(), nullable=True),
    sa.Column('bibliografia', sa.Text(), nullable=True),
    sa.Column('archivos', sa.Text(), nullable=True),
    sa.Column('discografia', sa.Text(), nullable=True),
    sa.Column('links', sa.Text(), nullable=True),
    sa.Column('otros', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bio_person')
    # ### end Alembic commands ###
