"""Increased size of several columns

Revision ID: dacc744dc3c8
Revises: e5b5d5705604
Create Date: 2018-08-07 00:24:10.777745

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dacc744dc3c8'
down_revision = 'e5b5d5705604'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('activity', 'name',
               existing_type=mysql.VARCHAR(collation='utf8_bin', length=40),
               type_=sa.String(length=80),
               existing_nullable=True)
    op.alter_column('event_type', 'name',
               existing_type=mysql.VARCHAR(collation='utf8_bin', length=40),
               type_=sa.String(length=80),
               existing_nullable=True)
    op.alter_column('history', 'operation',
               existing_type=mysql.VARCHAR(collation='utf8_bin', length=40),
               type_=sa.String(length=80),
               existing_nullable=True)
    op.alter_column('instrument', 'name',
               existing_type=mysql.VARCHAR(collation='utf8_bin', length=40),
               type_=sa.String(length=80),
               existing_nullable=True)
    op.alter_column('instrument_type', 'name',
               existing_type=mysql.VARCHAR(collation='utf8_bin', length=40),
               type_=sa.String(length=80),
               existing_nullable=True)
    op.alter_column('location', 'name',
               existing_type=mysql.VARCHAR(collation='utf8_bin', length=45),
               type_=sa.String(length=85),
               existing_nullable=True)
    op.alter_column('media_link', 'mime_type',
               existing_type=mysql.VARCHAR(collation='utf8_bin', length=40),
               type_=sa.String(length=80),
               existing_nullable=True)
    op.alter_column('person', 'first_name',
               existing_type=mysql.VARCHAR(collation='utf8_bin', length=40),
               type_=sa.String(length=80),
               existing_nullable=True)
    op.alter_column('person', 'last_name',
               existing_type=mysql.VARCHAR(collation='utf8_bin', length=40),
               type_=sa.String(length=80),
               existing_nullable=True)
    op.alter_column('premiere_type', 'name',
               existing_type=mysql.VARCHAR(collation='utf8_bin', length=40),
               type_=sa.String(length=80),
               existing_nullable=True)
    op.alter_column('profile', 'name',
               existing_type=mysql.VARCHAR(collation='utf8_bin', length=40),
               type_=sa.String(length=80),
               existing_nullable=True)
    op.alter_column('user', 'first_name',
               existing_type=mysql.VARCHAR(collation='utf8_bin', length=40),
               type_=sa.String(length=80),
               existing_nullable=True)
    op.alter_column('user', 'last_name',
               existing_type=mysql.VARCHAR(collation='utf8_bin', length=40),
               type_=sa.String(length=80),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'last_name',
               existing_type=sa.String(length=80),
               type_=mysql.VARCHAR(collation='utf8_bin', length=40),
               existing_nullable=True)
    op.alter_column('user', 'first_name',
               existing_type=sa.String(length=80),
               type_=mysql.VARCHAR(collation='utf8_bin', length=40),
               existing_nullable=True)
    op.alter_column('profile', 'name',
               existing_type=sa.String(length=80),
               type_=mysql.VARCHAR(collation='utf8_bin', length=40),
               existing_nullable=True)
    op.alter_column('premiere_type', 'name',
               existing_type=sa.String(length=80),
               type_=mysql.VARCHAR(collation='utf8_bin', length=40),
               existing_nullable=True)
    op.alter_column('person', 'last_name',
               existing_type=sa.String(length=80),
               type_=mysql.VARCHAR(collation='utf8_bin', length=40),
               existing_nullable=True)
    op.alter_column('person', 'first_name',
               existing_type=sa.String(length=80),
               type_=mysql.VARCHAR(collation='utf8_bin', length=40),
               existing_nullable=True)
    op.alter_column('media_link', 'mime_type',
               existing_type=sa.String(length=80),
               type_=mysql.VARCHAR(collation='utf8_bin', length=40),
               existing_nullable=True)
    op.alter_column('location', 'name',
               existing_type=sa.String(length=85),
               type_=mysql.VARCHAR(collation='utf8_bin', length=45),
               existing_nullable=True)
    op.alter_column('instrument_type', 'name',
               existing_type=sa.String(length=80),
               type_=mysql.VARCHAR(collation='utf8_bin', length=40),
               existing_nullable=True)
    op.alter_column('instrument', 'name',
               existing_type=sa.String(length=80),
               type_=mysql.VARCHAR(collation='utf8_bin', length=40),
               existing_nullable=True)
    op.alter_column('history', 'operation',
               existing_type=sa.String(length=80),
               type_=mysql.VARCHAR(collation='utf8_bin', length=40),
               existing_nullable=True)
    op.alter_column('event_type', 'name',
               existing_type=sa.String(length=80),
               type_=mysql.VARCHAR(collation='utf8_bin', length=40),
               existing_nullable=True)
    op.alter_column('activity', 'name',
               existing_type=sa.String(length=80),
               type_=mysql.VARCHAR(collation='utf8_bin', length=40),
               existing_nullable=True)
    # ### end Alembic commands ###
