"""Organization is now a many to many field

Revision ID: e00a198c270a
Revises: e30b975230b5
Create Date: 2018-09-20 16:30:04.751507

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e00a198c270a'
down_revision = 'e30b975230b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_organization',
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('organization_id', 'event_id')
    )
    op.drop_constraint('event_ibfk_3', 'event', type_='foreignkey')
    op.drop_column('event', 'organization_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('organization_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('event_ibfk_3', 'event', 'organization', ['organization_id'], ['id'])
    op.drop_table('event_organization')
    # ### end Alembic commands ###
