"""removed date

Revision ID: e30b975230b5
Revises: a0b0573c8941
Create Date: 2018-09-20 15:47:38.571282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e30b975230b5'
down_revision = 'a0b0573c8941'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('date', sa.DATE(), nullable=True))
    # ### end Alembic commands ###
