"""empty message

Revision ID: e5b5d5705604
Revises: 7ec4a103f691
Create Date: 2018-08-06 22:27:18.877723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5b5d5705604'
down_revision = '7ec4a103f691'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('history', sa.Column('timestamp', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('history', 'timestamp')
    # ### end Alembic commands ###
